### ISSUE TITLE
Crashes on Catalina 10.15.6

### ISSUE THREAD

**Issue by tongyin002** [Dygmalab/Bazecor#82] opened 2020-08-15 02:48 UTC
**Describe the bug**
Bazecore crashes randomly on mac os catalina 10.15.6

**To Reproduce**
There isn't really a pattern, at least from what I can tell. The GUI just crashes (turned into a white blank canvas) randomly. I feel it happens more often if I open Bazecore and not used it for a while. 

**Expected behavior**
Should not crash on mac os anymore.

**Desktop (please complete the following information):**
 - OS: mac os catalina 10.15.6
 - Bazecor Version: 0.2.2

**Additional context**
ICYWW, I updated the firmware to 0.2.2

**Comment by sebmartin** [comment] 2020-08-15 03:19
I'm experiencing the same issue. I can't use it for more than 1 or 2 minutes before it blanks deleting all unsaved changes. The only remedy that I've found is to quit and reopen the app which makes it very difficult to use. I'm also on 0.2.2.

**Comment by whimboo** [comment] 2020-09-03 11:14
Same here with Catalina.

As it looks like the Renderer (Electron) freezes and while staying in this state the application's UI
[Sample of Bazecor Helper (Renderer).txt](https://github.com/Dygmalab/Bazecor/files/5168063/Sample.of.Bazecor.Helper.Renderer.txt)
 is not getting updated. Also the application consumes a lot of CPU time. On my system it causes about ~150% CPU load. Attached you can find a sample from the activity monitor. 

This is most likely an Electron issue, which might have been fixed already. Note that the used version of Electron for this project is 7.1.12 while the last stable release is 10.x.

**Comment by trayo** [comment] 2020-09-09 16:43
Looks like a duplicate of #25 and has a trello story open here: https://trello.com/c/f7dHoDmA/28-showing-hardcoded-layers-can-easily-error-out

**Comment by sebmartin** [comment] 2020-09-11 12:37
#25 seems to focus on having the hard coded layers active.  I can trigger this without ever having them enabled.  I did have them on for a while when I first got this keyboard when I was just exploring through the UI and the options.  It does seem to happen far less frequently now that I have those off again.

I'll try to capture logs from the developer tools the next time it happens however if I don't have the dev tools enabled, I can't seem to open them at all since the keyboard shortcut doesn't work.

**Comment by trayo** [comment] 2020-09-12 02:01
I've also noticed that Bazecor crashes less when I have the developer tools open and wait for the `focus:` logging in the console tab to stop scrolling.

Essentially, after saving wait for the logging to stop before trying to save again. If you save while the logging is scrolling it seems to be a guarantee crash.

So I think the issue could possibly be mitigated by making the save button disabled until all saving processes have actually finished.

**Comment by AlexDygma** [comment] 2020-11-12 16:22
Hello All,

In this case as some have stated above the issue is related to #25 , there are multiple reasons this is happening, when you are in the editor and working actively, in some cases, the crash happens when the renderer function tries to update the keymap by reading it again from the keyboard, this can happen due to:
- micro interrupt in USB connection
- Timeout? in serial interface connection that crashes the focus.object?
- Anything that can break the focus API connection to the keyboard.

If you leave it be, another type of whitescreen crash happens, it's related to the electron version we are using (it's really old) and it's Chromium engine to render the application, it's a known bug that was solved later in time but we cannot update our dependencies due to Material.UI version 3.X and other interdependent software we need to update all at the same time.

so no fast fix for this, ill tell you we have been working in a new Bazecor that will solve all this issues getting away from the current package dependencies and making the base of the project updatable.

if we manage to undercover any solution for this problems we will update this thread.

**Comment by AlexDygma** [comment] 2021-04-19 14:09
Closed!

**Closed by AlexDygma** 2021-04-19 14:09 UTC
Labels: bug
