### ISSUE TITLE
Can not update Raise firmware with Bazecor 0.3.3 in Linux without bootloader mode

### ISSUE THREAD

**Issue by Mjasnik** [Dygmalab/Bazecor#207] opened 2021-04-21 21:18 UTC
**Describe the bug**
I can not update firmware with Bazecor 0.3.3 in ArchLinux without resorting to bootloader mode. The same happens in Manjaro.
Log files contain this:
```Neuron detected
Settings backed up OK
Resetting neuron
Waiting for bootloader
Bootloader didn't detect
Reset keyboard: Error: The firmware update couldn't start because the Raise Bootloader wasn't found. Please check our Help Center for more details or schedule a video call with us.

"serialNumber":"ILIKESERIALNUMBERSVERYMUCHraiseD"
"firmwareFile":"File has not being selected"
```
As a test, I have tried to update firmware with 0.3.1 version once again, it worked perfectly.
This is not the first time I do it, all releases previously starting I think with 0.2.3 were great success.

**To Reproduce**
1. Update Raise firmware through Bazecor without bootloader mode

**Expected behavior**
Update succeeds.

**Desktop (please complete the following information):**
 - OS: ArchLinux up-to-date
 - Bazecor Version: 0.3.3

**Additional context**
I have installed udev rules, firstly it changed ownership of the device ttyACM0, but after replugging the keybard, owner did not persist, it became uucp, which is strange, but that does not bother me as I added myself to uucp group way back when I got my Raise.
I tried to change the group to users too, that did not help.

I have updated firmware using bootloader mode, that completed successfully.

**Comment by kaschau** [comment] 2021-04-22 13:35
I am getting the same behavior on Ubuntu 20.04

v0.3.1 can flash just fine. Using an AppImages beyond 0.3.1 cannot find bootloader, lights just stay on.

**Comment by GazHank** [comment] 2021-04-23 22:51
Based on a fresh install of Ubuntu 20.04 I think I'm able to recreate the same issue.  For me, if I select the firmware update option then the keyboard switches to rainbow LED mode, however at the end of the countdown, despite pressing the Escape key the keyboard never resets to enter bootloader mode.  The toast pops up to say the firmware update could not start because the bootloader wasn't found, but the keyboard is still in normal mode with the LEDs still in rainbow effect mode.

I've had a little excursion through some of the recent patches, and the closest I can find to resolving this is if I rollback the serialport package from v9 to v8.  V8 allows the keyboard to enter bootloader mode, but the update doesn't complete so this is not a valid fix or workaround.  I should also highlight that I tried reverting some of the recent changes to timeout values and this seemed to have zero impact on this issue.  Hopefully I'll get some time to dig a little deeper over the next few days, but I thought I'd share those initial findings incase it helps anyone else diagnose or fix this.

So far base on testing to date, it looks like the issues with connectivity only relate to entering bootloader mode, as 0.3.3 seems to be able to read and write data to and from the keyboard in all other cases tested so far (e.g. preferences, layer info, colour palette, macros etc. etc.)

**Comment by alejandrocen** [comment] 2021-04-24 09:25
Same problem with Pop!_OS 20.10

**Comment by GazHank** [comment] 2021-04-24 19:17
So some progress to report on...

It looks like we have a couple of problems at play:

1. Resetting the keyboard (invoking DTR) - I'm still investigating why `port.set({ dtr: true }...` suddenly doesn't work on serialport v9.  I'd had some success at forcing the status by sending other messages to the keyboard or reading data, however if we just wait for the timeout, then the reset just doesn't happen.
2. Access rights - It looks like the keyboard has a different product ID when in bootloader mode (2200 vs 2201 when in normal use).  As such we need to grant access to both products.

For the second point it looks like we just need to add the extra product code into the sudo.exec, it's currently:
``echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2201", GROUP="users", MODE="0666"' > /etc/udev/rules.d/50-dygma.rules && udevadm control --reload-rules && udevadm trigger`,`
        
We can of course workaround the keyboard reset problem in the short term by pressing Escape when the keyboard is plugged in, but I'd like to get to the bottom of the problem, as that's not really a sensible suggesting for an end user.

I hope to get more time to take a look soon

Cheers

Gareth

ps - the only other think to flag is that I believe serialport v9 removed support for 32bit on Linux.   This doesn't seem to be the cause as I'm running 64bit version of Ubuntu, but thought I would mention it just in case that affects anyone

**Comment by Mailaender** [comment] 2021-04-25 14:46
I can confirm this fails since 0.3.2 on @openSUSE.

**Comment by Mjasnik** [comment] 2021-04-26 06:32
Thanks @GazHank for looking into this, I have a question about this:
```echo 'SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="2201", GROUP="users", MODE="0666"' > /etc/udev/rules.d/50-dygma.rules && udevadm control --reload-rules && udevadm trigger```

If permissions are set to 666, which implies that any user can read/write to the device file, why trying to set group to ```users```?

To me it should make sense to either set group to ```users``` and force everyone to add oneself to ```users``` group to allow to write to the device file, or just leave whatever the group is and allow anyone to write to the device without forcing the specific group.
Does this makes sense?

**Comment by GazHank** [comment] 2021-04-26 07:30
Hi @Mjasnik,

I haven't looked into the udev rules in much detail yet, so far I've just replicated the working rule for normal mode operation for the boot loader mode.  I've tried to make any fixes as small as possible to avoid any regressions elsewhere.

It might be worth trying alternative rule definitions if you think that might improve things.  I should note that the upstream repo have revised their rules so we might want to implement something similar: https://github.com/keyboardio/Chrysalis/blob/master/static/udev/60-kaleidoscope.rules

**Closed** 2021-04-29 14:30 UTC
Labels: bug

**Comment by GazHank** [comment] 2021-05-26 21:33
Hey @AlexDygma we should be able to update to version 9 of serialport again soon, as the fixes have recently been incorporated (https://github.com/serialport/node-serialport/commit/015bc17996721c92746e44e797b1a3d899076af1)

ps - on an unrelated matter, we may start to see issues for users of the new Apple M1 devices being unable to update the firmware (https://github.com/serialport/node-serialport/issues/2243) - other functionality should not be impacted, but I wanted to flag it so that time isnt wasted trying to trace this know issue.  From what I can tell, the only issue for us is the set DTR functionality, so as always people can always force the bootloader mode by holding ESC when the device is plugged in... but that's not a nice workaround, and it would be nice if we could help fix the upstream serialport package :-)
