### ISSUE TITLE
One Shot Layer (OSL) exits on modifier key down event

### ISSUE THREAD

**Issue by mtalexan** [Dygmalab/Bazecor#101] opened 2020-10-05 20:32 UTC
**Describe the bug**
One shot layer (OSL) exits the layer when modifier keys are pressed/held, preventing the layer from allowing modified single key presses.

**To Reproduce**
1. Configure a key for OSL to another layer, and configure a specific underglow color for the layer uniquely
2.  On the one-shot layer set all keys to No Key, and configure the underglow color for the layer uniquely
3. On the one-shot layer, configure some modifier keys (Left Alt, Left Ctrl, Left Shift, Left Win, etc)
4. Configure the computer so Alt+F4 will close the current window (standard on many OS configurations)
4. On the one-shot layer, configure a key to be the F4 key, and make sure it is not identically configured on other layers
5. Save the config
6. Open a window that can be closed as part of the test
7. Tap the OSL key
8. Press and hold the Alt key, then tap the F4 key

**Expected behavior**
The test window is closed.  The underglow color changes back to the Layer 0 color after the F4 button is pressed/released.

**Actual behavior**
Nothing happens, the underglow color changes back to the Layer 0 color as soon as the Alt key is depressed (even before it is released)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.2

**Additional context**
* If only tapping F4 without any modifiers from the OSL layer, the F4 key is sent and the layer switches back (as expected)
* Problem persists regardless of whether Transparent is used for one of the keys.  Using it for both will produce the same effect regardless of the layer it's triggered from and wouldn't be conclusive for this test/bug.

**Comment by kkckrnz** [comment] 2020-10-29 14:23
This isn't a bug. It's intended to work this way, as described in dygma's website.
```
Single-tap: the next keypress will be affected by the layer shifting.
After that keypress, you are back to the initial layer.
```
What you can do instead is,
1. tab `Alt (One Shot Modifier)`
2. tab `Layer key (One Shot Layer) that has F4 key`
3. tab `F4`

**Comment by mtalexan** [comment] 2020-10-29 14:54
As you quoted, "on key press". That doesn't indicate key down or key up.

If it transitioned back to the old layer on the key up event of any key, it would allow modifiers to be used in combination with the OSL because the modifier keys remain down until the non-modifier key is pressed, then one or more are released. 
Doing it on key up also means it doesn't necessarily have to handle the more complicated case of a non-modifier key being already down when transitioning between layers, possibly leaving it to the end user to resolve for modifier keys.

**Comment by kkckrnz** [comment] 2020-10-29 16:22
> As you quoted, "the next key press". That doesn't indicate key down or key up. And the "after the next key press" suggests it should be key up.

I think the meaning of "press" here is clear. key down is `press`, key up is `release`. "after the key press" means "after the key down event".

However, I understand what you are suggesting and how it could be useful for using modifiers in combination with other keys.

What I'd rather suggest is to keep the current behaviour for all keys but make an exception to modifiers. So if any modifier keys are pressed (key down event), layer won't transition back to initial layer until modifier keys (eg. `Alt`) are released (key up event) or until the next key (eg. `F4`) is pressed (key down event).

The reason why I want to keep the current behaviour for the other keys is that if it waits for the `key up` event, it will not give immediate feedback to users.

**Comment by mtalexan** [comment] 2020-10-29 16:42
That interpretation makes sense as well, and I agree that it wouldn't necessarily be ideal to switch everything to key release for the OSL return.  That's partially why I filed this with a user-need description rather than a more technical request.

**Comment by AlexDygma** [comment] 2020-11-13 15:04
> That interpretation makes sense as well, and I agree that it wouldn't necessarily be ideal to switch everything to key release for the OSL return. That's partially why I filed this with a user-need description rather than a more technical request.

Hello there @mtalexan !

So what actually happens when you press OSL is that at keyDown event, the active layer is switched to the OSL assigned one, this means anything you press after that will have to be in that layer, if you need to do something like pressing more than one button at the same time, the best way you can do it is to use shift layer instead, it will work just as any modifier and you can stack it (ofc all in the same layer), but as @kkckrnz suggested, you can in fact press first the modifier and then do the modified action.

but for now i'll close this issue as it's not a bug but a feature request, if you are really keen on having this, please fill one and we will try to implement the feature in the near future.

**Closed by AlexDygma** 2020-11-13 15:04 UTC
Labels: bug
