### ISSUE TITLE
Bazecor 1.3.9 Brightness sliders not working (Windows)

### ISSUE THREAD

**Issue by AlDorado9000** [Dygmalab/Bazecor#665] opened 2024-01-16 23:33 UTC
In the settings menu the brightness sliders for the keys and underglow do not work. I have the wired model and the firmware update to 1.2.5 did not help either. The software saves the settings but nothing changes, even when reconnecting the keyboard.

Edit: The toggle for the LEDs does not turn them off or on (only the Neuron turns LEDs off and on) but this toggle makes the brightness apply!

**Comment by PapaNappa** [comment] 2024-01-17 07:49
Same here with my Defy.

The "Time before LEDs turn off" does not apply either. I have set it to 5 minutes, and even after 30 minutes of no interaction (out for lunch), the LEDs are still on. This is particularly annoying when sending the computer to sleep mode, but the Defy will glow for ever.
Should I create a separate issue for that? Seems kind of related, since it’s all to do with the LED settings in the preferences.

The workaround for me right now is to cycle through the LED effects until this "afterglow" effect is active, where the backlight is off, and only turns on for keys you press, then fading away.

I am also using latest Bazecore 1.3.9 with Defy firmware 1.2.5-beta.

**Comment by alexpargon** [comment] 2024-01-17 10:06
Hey there @AlDorado9000 @PapaNappa! Is this happening with a wireless Defy or a wired version?

I'm working on a fix for this on the wired version, but not on the wireless, so please let me know if you have wireless hardware.

**Comment by PapaNappa** [comment] 2024-01-17 10:54
Mine is wired only.

Great to hear you are already working on it!

**Comment by AlDorado9000** [comment] 2024-01-17 14:20
Mine is also wired only. I kept the original 5 minutes timeout and for me the underglow did turn off but the keys stayed on. After waking it up (if I recall correctly) the underglow did not turn on until I used the LED toggle key.

**Comment by PapaNappa** [comment] 2024-01-17 14:47
I do not have underglow, so that’s why I did not see any LEDs turning off after the timeout or with the LED toggle key.
However, I would expect both to affect the key LEDs as well.

**Comment by AlDorado9000** [comment] 2024-01-17 19:46
Correction: The underglow does turn off and on as intended, the keys do not.

**Comment by AlDorado9000** [comment] 2024-01-18 19:04
Update (again): Today I timed it and only the neuron turns off and on after the set time.

**Comment by levihilton** [comment] 2024-01-21 03:42
I also am experiencing this issue on a wireless keyboard, but I have only had issues with the wired settings. The keyboard lights stay on indefinitely when plugged in.

**Comment by AlDorado9000** [comment] 2024-01-21 04:15
On the topic of brightness, would it be possible to add a brightness slider for the neuron as well? It is much brighter than the keyboard with the same color as the underglow and does distract as it is in my field of view. I used quite a number of different colors already and I don't have enough color slots left to make dark underglow color versions.

**Comment by alexpargon** [comment] 2024-01-25 13:40
@AlDorado9000 Ofc, no issue here, i will push the solution to this problem with the added brightness bar for the Neuron.

The issue is on the FW's team hands, as after some tests we verified it to be 100% FW related.

they are working on it now, before making 1.2.6 stable, they will add this fix!

**Comment by AlDorado9000** [comment] 2024-01-25 17:55
Thanks for the update and the support!

**Comment by PapaNappa** [comment] 2024-02-23 07:03
I can confirm this bug is fixed for me with the latest 1.2.7-beta firmware.
Thanks a lot!

**Comment by AlDorado9000** [comment] 2024-02-23 07:54
Works for me too on 1.2.7-beta. Now the brightness sliders apply with the save button, the LED-off timer works and the LED on/off key works as well.

**Comment by alexpargon** [comment] 2024-02-23 14:38
👏🏻👏🏻👏🏻

Glad to hear it! closing this issue then!

**Closed as completed by alexpargon** 2024-02-23 14:38 UTC
Labels: bug
