### ISSUE TITLE
Attempting to set up build environment

### ISSUE THREAD

**Issue by jasperandrew** [Dygmalab/Bazecor#29] opened 2020-01-09 20:10 UTC
I'm just trying to set up the build environment so I can mess around and see if there's anything I can contribute, but unfortunately yarn fails to complete successfully. I've attached the output of the command. I feel like this probably isn't the best place to ask for this sort of help, but I'm not sure where else I would go. If anyone knows a better place, let me know. Thanks!
[out.txt](https://github.com/Dygmalab/Bazecor/files/4042293/out.txt)

**Comment by algernon** [comment] 2020-01-22 10:27
This appears to be the same as #24, or keyboardio/Chrysalis#452: We need to update the `serialport` dependency, because it does not work with Node >= 12. However, simply upgrading it will result in a Bazecor that compiles, but doesn't work, so it's a bit more involved than bumping a dependency.

I'm closing this in favour of #24, since the root cause is the same.

**Closed by algernon** 2020-01-22 10:27 UTC
