### ISSUE TITLE
Specific conditions still cause "upload layers" to hang

### ISSUE THREAD

**Issue by alexvy86** [Dygmalab/Bazecor#139] opened 2020-11-26 02:48 UTC
**Describe the bug**
When I click "upload layers" Bazecor hangs for some layer configurations.

**To Reproduce**
1. Open Bazecor
2. Load the `Layers-hangs.json` file from the zip file below
3. Click on the button to upload the layers to the firmware
4. Uploading process hangs and the keyboard becomes unresponsive

**Expected behavior**
Any possible settings for layers upload correctly

**Screenshots**
This is the developer tools console after clicking on Upload layers. It just hangs there indefinitely until I close Bazecor.

![image](https://user-images.githubusercontent.com/716334/100301863-b7ae0b00-2f5e-11eb-9010-0d73cc2e7769.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Bazecor Version: 0.2.4

**Additional context**
[This zip](https://github.com/Dygmalab/Bazecor/files/5600162/Layers.files.zip) contains two almost identical files, one that works, and one that causes the hang. The only difference is the color of one key in layer 7, as seen in the screenshots below.

![image](https://user-images.githubusercontent.com/716334/100301996-f93eb600-2f5e-11eb-9a59-d5c01f530b5a.png)
![image](https://user-images.githubusercontent.com/716334/100302028-0d82b300-2f5f-11eb-86af-b826bd0fa472.png)

Probably related to #31 ?

**Comment by alexvy86** [comment] 2020-11-26 02:54
Some more Layers files that didn't work during my tests: [Layers - also don't work.zip](https://github.com/Dygmalab/Bazecor/files/5600179/Layers.-.also.don.t.work.zip)

**Comment by AlexDygma** [comment] 2020-11-26 07:15
Hello @alexvy86 !

Great research work! 👍 

I'll get into it now, this will be fixed for 0.2.5 for sure.

**Comment by AlexDygma** [comment] 2020-11-26 09:06
So, @alexvy86, i imported the layers you shared but it didn't fail when saving them, can you make a global backup of your layout using the button on the uppermost right. 

if this is truly repeatable even restarting the computer and changing the cable of the port, ( the normal origin of errors when uploading data is a lack of response from the serial port due to a micro disconnection or a wrong number of elements being send that trigger an overflow in only some circumstances).

this being said, this can also be an issue relating to connection speed and data transfer rate.

either way, the layer should be uploadable if you switch computer, as in mine it works, so please tell me more! 😆

**Comment by AlexDygma** [comment] 2020-11-26 09:57
> So, @alexvy86, i imported the layers you shared but it didn't fail when saving them, can you make a global backup of your layout? use the button on the uppermost right.
> 
> if this is truly repeatable even restarting the computer and changing the cable to another port, i need more info ( the normal origin of errors when uploading data is a lack of response from the serial port due to a micro disconnection or a wrong number of elements being send that trigger an overflow in only some circumstances).
> 
> this being said, this can also be an issue relating to connection speed and data transfer rate.
> 
> either way, the layer should be uploadable if you switch computer, as in mine it works, so please tell me more! 😆

Hahaha, so now testing the keyboard i flashed, i realized you indeed did send the whole layers backup, but as i said, none of this are failing, so try the cable / usb port repositioning test to rule out bad connectivity and if that keeps failing ill try to reproduce your environment to make the bug appear.

**Comment by HomerSp** [comment] 2020-11-26 12:55
I had a look at this and I am in fact able to reproduce it. This is a really, really weird issue - I added some debug code to see what's being written (in the serial port code) and some code to the firmware to see what's being received.

In the firmware I added this:
`    char buf[4096];
    size_t len = Runtime.serialPort().readBytesUntil('\n', buf, 4096);
    Runtime.serialPort().print(len);
    Runtime.serialPort().print(" - ");
    Runtime.serialPort().write(buf, len);
    Runtime.serialPort().print('\n');`

As a test I'm sending this:
`colormap.map 3 1 1 1 1 1 1 10 12 12 12 12 12 10 4 4 4 4 12 10 4 12 12 12 12 12 11 10 10 3 3 7 1 3 12 12 1 1 1 1 10 12 12 12 12 12 12 12 12 12 4 4 4 4 12 10 12 12 12 12 12 12 1 10 10 3 3 7 1 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 10 10 10 10 10 10 1 4 4 4 4 4 1 12 12 12 12 4 1 4 4 4 4 4 4 14 12 12 4 12 7 3 1 4 4 10 10 10 10 3 4 4 4 4 4 4 4 4 4 12 12 12 12 4 12 4 4 4 4 4 12 1 12 12 6 6 10 8 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 8 8 8 8 8 8 4 3 6 1 6 3 4 11 1 1 1 15 4 15 4 4 4 4 15 14 4 4 1 1 10 3 5 8 8 8 8 8 8 3 15 15 11 11 4 4 11 15 11 11 11 4 4 11 4 1 11 11 3 3 12 1 1 1 1 1 10 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 11 8 8 8 8 8 8 11 11 11 4 11 11 11 11 4 4 4 11 11 1 11 11 11 11 11 14 1 1 1 1 1 1 1 1 11 8 8 8 8 1 11 11 4 4 4 11 11 1 11 11 4 4 4 11 11 11 11 11 11 11 12 1 1 6 6 6 1 1 1 1 1 1 1 1 1 1 11 1 1 1 1 1 1 1 11 1 1 1 1 1 1 5 9 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 8 8 8 8 8 8 4 15 11 1 15 15 4 11 1 1 1 15 4 15 15 15 15 15 15 14 4 4 1 1 10 3 5 8 8 8 8 8 8 3 15 15 10 9 9 9 10 15 10 10 9 9 9 10 4 1 9 9 9 10 12 1 1 1 1 9 10 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 3 10 10 10 10 10 10 1 4 1 4 4 4 1 1 1 1 4 4 1 4 4 4 4 4 4 5 12 12 3 3 3 6 3 4 4 10 10 10 10 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 12 1 12 12 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 12 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 11 11 11 11 11 11 11 11 11 11 11 11 11 1 11 11 11 11 3 14 11 11 11 11 11 11 1 11 11 11 4 4 4 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 12 11 11 11 1 11 11 11 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 10 10 10 10 10 10 1 4 4 4 4 4 1 4 4 4 4 4 1 1 4 4 4 4 4 5 4 6 1 1 1 1 1 4 4 10 10 10 10 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 4 4 4 4 12 6 4 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 6 7 7 7 7 7 7 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 8 4 4 5 5 1 1 4 4 4 7 7 7 7 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 12 6 7 4 5 5 1 1 5 5 2 2 2 2 2 2 1 1 1 1 1 1 1 5 5 3 3 3 3 3 3 3 3 5 5 5 5 5 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1`

Everything looks to be sent properly, but on the receving end not everything is read because the data looks to be cut off. If I send the above, only the first 2803 characters are received (only data, not including the command name). I tried increasing the read timeout, but that doesn't do anything other than increase the time it takes for it to return the cut off data. While it's attempting to read the remaining data and before the timeout the keyboard keeps sending the return character over and over too.

If I echo the data straight to the ttyACM0 port things get even weirder... Using the example above, I get the first 2803 characters. But when running it a second time I get 2739, and then 2675 - it looks to be decreasing by 64 on each attempt. On the fourth attempt I get the expected 2866 characters, and after that it goes back to 2803 and repeats.

This is all very weird, but I do have a potential solution/workaround. I've noticed that it does this when writing an even amount of characters/data - if I, for example, add a space after the data above it always works and is never cut off.

**Comment by AlexDygma** [comment] 2020-11-26 16:14
Wow @HomerSp, u managed to nail it, i was testing this in Mac and couldn't reproduce, now in windows is happening to me also.

I'll try to invest some time to know why it's happening but your workaround will be pushed to 0.2.5 for sure.

Good work!! and thanks a bunch!! 🤗

**Comment by alexvy86** [comment] 2020-11-26 16:24
Glad to hear it finally did reproduce on your end @AlexDygma :). I'll try with a different USB port and restarting the computer just to be sure and to get the data points. I'm inclined to think it won't make a difference because if it was a connectivity issue I'd expect to see more failures for any layers configuration, but the ones that work seem to always work, and the ones that fail always fail.

@HomerSp 's findings make sense to me, in a way, because both in #31 and in this issue, the only difference between a working and a failing config is that one of them has 1 additional character. (Now, what kind of bug would cause that, I don't have any good theories). I bet we can make it hang reliably by just changing the colors of some keys, as long as we maintain the amount of data transmitted an even number.

**Comment by HomerSp** [comment] 2020-11-26 20:30
@AlexDygma I can see that OSX (darwin) uses a different method of writing data to the serial port - it looks to be sending the data in chunks, split by spaces. I actually tried forcing that path earlier, and it worked too, but I didn't really understand why it did. But now that I look at it I can see that it adds a space after each data chunk, which would, possibly, explain why it works on OSX. That path is considerably slower than sending it all in one chunk though, and it doesn't really increase reliability on non-OSX, so I don't really see much point in switching to that permanently.
You can see the relevant commit from chrysalis here: https://github.com/keyboardio/chrysalis-api/commit/85b2e8495581fca03678aab8724ba9e06d54f2cb

I still don't really understand why the length being even or uneven would cause it to not send all of the data, but I'll continue looking! I do know it has nothing to do with the actual length of the data as the data of my custom colormap is significantly longer and there's no problem whatsoever there.

**Comment by HomerSp** [comment] 2020-11-27 10:48
Done some more digging, and I think I have found the problem and the proper solution. I looked at wireshark, and it sends the data above in three different packets. The first two have a data size of 1280, and the last one is 320 bytes. I think the problem is that it doesn't send an end of transfer properly when doing multi-packet transfers. If I look at the SAMD21 code it uses a buffer size of 256 bytes and 1280 is divisible by 256, but 320 is not - there will be 64 bytes left which matches what I saw above. I think the problem is that the remaining data is exactly 64 bytes, which is the maximum packet size - sending an additional character would increase that to 65, which I'm guessing forces it to pull in the data.

I found this commit too which helped a lot in trying to narrow it down: https://github.com/arduino/ArduinoCore-samd/commit/3316756b0ce32d334b8798206c5bb88984b396b1

So to properly fix this you could simply cherry-pick that commit (it would require manual editing though), or change the bufferSize in the DoubleBufferedEPOutHandler constructor call from 256 to 64 (either works, I've tested both). I can do a PR if you'd like.

**Closed** 2020-11-27 16:29 UTC
Labels: bug
