### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by davidm2m** [Dygmalab/Bazecor#114] opened 2020-11-10 10:18 UTC
**Describe the solution you'd like**
Dark theme with a selector at settings menu.

**Describe alternatives you've considered**

**Additional context**
Background color chooser, but need to change font color with dark colours.

I know that a dark theme is not a accesibility thing but for people like me, with visual problems, a bright background is annoying.

**Comment by Lite5h4dow** [comment] 2020-11-12 13:44
there seems to be a dark theme in the code I'm assuming there is no way to select it currently? (i don't have a keyboard yet to really use Bazecor)

**Comment by davidm2m** [comment] 2020-11-13 14:16
I don't know if the dark theme is on the source code, but not have a button like Chrysalis anywhere

**Comment by HomerSp** [comment] 2020-11-20 11:50
There is indeed a dark mode theme, which can be enabled in the code. It mostly looks fine, but there are certain parts that don't look right with it enabled, so I'm guessing it hasn't been prioritised, and that's why there isn't a toggle in the UI.

**Comment by Lite5h4dow** [comment] 2020-11-28 09:17
I might take a look at that today, no promises since I haven't really learnt the codebase yet

**Comment by GazHank** [comment] 2021-03-22 22:39
@davidm2m would you bee able to confirm the areas of the app where you are facing issues?  I've proposed some fixes for white text on very white backgrounds as part of the firmware update part of the app.  Is it primarily the color selection on the LAYOUT & COLORMAP EDITOR screen that you are referring to?

**Comment by davidm2m** [comment] 2021-03-23 14:51
@GazHank I refered to the hole app, I normally use dark theme in Win10 and when I have light backgraound with black letter I switch to the inverted colour pattern of Win10, but the problem is to chose colours or see what colour have any led of the keyboard, because of it I like to see the dark theme in bazecor.
![bazecor](https://user-images.githubusercontent.com/65335217/112165971-8208ee00-8bef-11eb-8f61-c13dae2e3d57.png)
This is Bazecor with inverted colours.

I don't know how to program or compile for Bazecor, I only try to help with feedback of the stable version and betas, and with new enhadments that I think that can be useful for other users.

**Comment by GazHank** [comment] 2021-03-23 15:44
@davidm2m Ah my bad, I thought you were using a dark theme in Win10 (under settings, personalisation, colours), but I understand you are using a light theme and the inverted colour mode (found under accessability options), is that correct?

Theme settings:
![image](https://user-images.githubusercontent.com/64541249/112171789-12453400-8bec-11eb-8c8c-dc3811ab9ee0.png)

Inverted color filkter:
![image](https://user-images.githubusercontent.com/64541249/112172005-3bfe5b00-8bec-11eb-907d-fd0a5b28d320.png)

BAZECOR with dark theme (no colour inversion):
![image](https://user-images.githubusercontent.com/64541249/112172212-6d772680-8bec-11eb-98bb-18622cf503b1.png)

Have you tried the dark theme (without inversion) in windows, or is it too problematic with the other apps that you use?  If you are really keen to keep the colour inversion I could see it is possible to (re)invert the colours of the keyboard and palette, and add this as an option under settings?

**Comment by davidm2m** [comment] 2021-03-23 17:06
@GazHank I use the dark mode in Windows 10, but when the app don't have dark mode I use inverted colours in accesibility using the hotkeys to switch it.
I don't have the option to switch bazecor to dark theme, it will be awesome if I can do it. With the dark mode I don't need to invert the colours.

**Comment by AlexDygma** [comment] 2021-03-31 12:20
I merged some of the work of @GazHank on this new revision, wont close this issue but we are nearer 👍

**Comment by davidm2m** [comment] 2021-03-31 12:25
In the new revision is possible to active dark mode?? (with settings change or some flag in the shortcut??), I like to try the changes and give feedback about the dark mode.

**Comment by GazHank** [comment] 2021-03-31 14:09
Not yet I'm afraid, in the latest patches (not yet incorporated) the theme is set based on you system theme, but I think I'll add a toggle in the preferences panel so that you can switch between light, dark and system settings.

I could share binaries of the dev code if you are unable to compile it, but you might be better waiting a couple of days for us to iron out some of the known issues

**Comment by davidm2m** [comment] 2021-03-31 17:47
If I don't missunderstood in the new 0.3.0 version dark mode is not set automatically with system theme, because I install it and bazecor continue using light theme.

I don't have any problems to wait for the next version (with the patches for dark theme), If you need some testing give me a binaries and don't have problem to try it.

**Comment by GazHank** [comment] 2021-04-02 21:07
Hi @davidm2m,

I thought I'd drop you a brief update as the fixes for this were taking a lot longer than I hoped.  The macro sections of the code needed quite a lot of work to make them functional and readable in both colour modes as much of the screens we handcrafted and hardcoded to one display mode.

The good news is I now have functional and usable verison of the theme changes working based on the 0.2.8 code base.  My next task is to upgrade it to 0.3.0 and then to parcel it up so that it can be included in the main development branch.

By way of a preview, here are how the screens look in dark theme:
![image](https://user-images.githubusercontent.com/64541249/113453351-b5245c00-93fd-11eb-9a4e-2148d34bd499.png)
![image](https://user-images.githubusercontent.com/64541249/113453409-d127fd80-93fd-11eb-8bd2-91b40464d82d.png)
![image](https://user-images.githubusercontent.com/64541249/113453447-e1d87380-93fd-11eb-9a95-f11b1a07cb3d.png)
![image](https://user-images.githubusercontent.com/64541249/113453502-06cce680-93fe-11eb-9696-29640ccdcdc1.png)

The nice thing is that with the exception of a few stubborn bits of functionality we can completely theme the entire app, so if you really like pink and purple you can create something like:

![image](https://user-images.githubusercontent.com/64541249/113453848-ce79d800-93fe-11eb-914e-a3865f8843f3.png)

I'll try to keep you informed on the progress, and perhaps package up an experimental release you you once I've got it close to the 0.3.0 build.  The biggest aspect of testing will be to make sure there are no regressions when everything is bolted together.

Hope you are having a great easter!

Gareth

**Comment by davidm2m** [comment] 2021-04-03 07:14
Awesome @GazHank !!

Taking a look of the screenshots I can't see any readability issue.

Maybe, (it's only a fast idea) the change of colour accent in the macro keys can be linked to the layer blow colour or key backlight colour (I think that can be a need pro touch) and can work as a remainder of the key you are modifing.

**Comment by GazHank** [comment] 2021-04-03 07:40
Oh I like it.  I don't think that will be super quick, due to the need to check that the readability is maintained irrespective of the funky colours the user chooses, and making sure that this works on both light and dark themes. I'll certainly add this to be list of things to try :-)

**Comment by AlexDygma** [comment] 2021-04-03 08:13
Hey @GazHank !

Awesome work! 

Im going to push a few more UI tweaks to the new preferences options, you can view them on the PR #190, take them into account if you are going to tackle with the preferences panel also!

Btw, there is already a toggle button at the preferences panel for the Dark Mode, it's just commented out as the mode was highly unstable and didn't work well without resolving all the quirks that some screens had, so to enable it just uncomment the lines!

If you need my assistance just tell me! im impressed with the amount of effort you put into this, it's the least i can do 😄

**Comment by GazHank** [comment] 2021-04-04 01:29
Ok, so I've got a version which is up to date with development, if you want to take it for a spin then you can find it at https://github.com/GazHank/Bazecor/releases/tag/0.3.1-Alpha.1

Given the dark mode support is still experimental I've "hidden" the option under preferences -> advanced per the screenshot:
![image](https://user-images.githubusercontent.com/64541249/113495549-951e9680-94ea-11eb-86ed-031c2fe2de75.png)

please note that you will need to close and reopen the app after making the switch as I need to try a few things to get the themes to reapply on the fly.

@davidm2m let me know if you have an issues or notice any weird quirks - I'm sure there will be some

@AlexDygma This should be pretty up to date with dev, and I've pulled #190n in to the code, although as you will see above I got a little carried away with the sliders, let me know if you like it, of course its pretty easy to revert that stuff or tweak it.

More importantly I've added some build instructions to the release.  Windows needs the packages built from source; but I don't know if you can just strip that stuff away on Mac and Linux (if the packaged binaries arent messed up).  I've also noticed that there are some mac issues in the serialport repo, but not sure if they are affecting you (e.g. https://github.com/serialport/node-serialport/issues/2232) .  If you are still facing issues on Mac, I wonder if it might be worth trying a slightly older version of that package?

Please feel free to share any errors you see, I've seen quite a few different problems on WIndows while trying to sort out that serialport mess.

If it helps I could try pulling together some incremental pulls which upgrade the fundamental pacakages bit by bit, I'd avoided this initially as some of the upgrades really screw the UI (both layout and usability).

All feedback welcome

have a great weekend!

Gareth

**Comment by davidm2m** [comment] 2021-04-04 09:48
I was taking a look in the @GazHank alpha, and I have a few tweaks:

- Make preferences to use not all width of the scrren (I use a 21:9 monitor and maximized) (Maybe this is for other place @AlexDygma )
![preferences snapshot](https://user-images.githubusercontent.com/65335217/113504793-b4ddab00-953a-11eb-80f0-7b3a84069bf9.png)
and I the same problem in the keymaper
![key picker](https://user-images.githubusercontent.com/65335217/113504808-d63e9700-953a-11eb-991e-39376db0d97e.png)
- Custom colour picker don't use dark background (I think that is better with dark background and maybe a bright border).
![custom colour picker](https://user-images.githubusercontent.com/65335217/113504818-ebb3c100-953a-11eb-9406-1eebff24190a.png)
- A little movement in the Raise part when a change is waiting to be upgrade in the keyboard. Maybe is hard to see the diference.
![movement in the upper side](https://user-images.githubusercontent.com/65335217/113504828-0c7c1680-953b-11eb-819f-a361a1c10558.png)
- And In macro editor, the displacement bar is like the bright theme, I don't know if it is possible to make dark like in windows dark mode.
![macro editor](https://user-images.githubusercontent.com/65335217/113504861-6086fb00-953b-11eb-9316-c5a272c12daa.png)
I my firt look I don't see anything more.

**Comment by GazHank** [comment] 2021-04-04 15:02
Thanks @davidm2m,

Nice to meet another member of the ultrawide monitor club <high five!>

**Window Sizing**
 The window sizing is currently broken in a few ways:
- Screens / components that don't scale well to large monitors (/windows) like preferences and the key selector
- Screens / components which don't make any use of large screen space, such as the macro editor which is fixed to a "tiny window"
- Screens that don't scale well to small screens (I've actually added a minimum size in this dev build to avoid the worst issues, but it still needs to be looked at for those poor souls on old laptops)

At the moment I think I've squished all of the sizing bugs that were introduced by the package changes, and the remaining issues simply remain from the original code base.  As such I'm treating all of these sizing problems as a separate issue, which I'd like to go back and fix, but not something which I think we need to fix to get the these changes into Prod.  

_The annoying thing is that I've got a few ideas for the enhancements/fixes, but the top prority has to be to get the package upgrades into the main code base as that will allow us to use some of the new tech to fix things more quickly and easily in the future_ 

If you think any of these are show stoppers or see any problems or regressions compared to the current 0.3.0 then please shout and I'll bring them up the priority list.

**Custom color(/colour) picker**

Good spot! Opps, sorry that one should have been on the TODO list.  I'll add a note into the code so that I remember :-)

At the moment we use https://casesandberg.github.io/react-color/ for the colour selector, and in particular we use their "Sketch" picker.   As you can see from their examples none of the out-of-the-box pickers seem to maintain the required level of functionality while being easily Dark themable.  As such I think we would need to make a custom picker, which is very do-able, but probably an item for the future enhancement list rather than a show stopper for release due to it's size vs benefit?

**Movement when change is pending**

Wow, thanks for spotting this, it looks like the production 0.3.0 version has a very tiny "twitch", but the way that spacing and margins work in the new versions of material-ui have made this "much" worse.  I'll see if I can trace this bug down and fix it :-)

**Displacement bar**

Sorry I wasn't sure which element you are referring to?  is it the "scrollbar"?

If so, it looks like something that has been a missing feature of material-ui for some time without resolution (https://github.com/mui-org/material-ui/issues/9919).  There do seem to be some packages we could use to address this (e.g. https://www.npmjs.com/package/@vdjurdjevic/material-scrollbars).  I am however not sure of the maturity or stability of the packages so would like to investigate a little more before adding any extra packages into the code base.

Thanks for the feedback, and do keep it coming.  I'll keep you posted when I have any fixes or new builds to try.

Gareth

**Comment by GazHank** [comment] 2021-04-04 16:06
Looks like moving keyboard was due to a custom menu icon that we use which is about 12 pixels taller than the close/cancel button, so the bar resizes when we change the icon; a nice quick fix once I found it :-)

The "twitch" I mentioned is when the "progress bar" thingy runs along the bottom of the menu bar.  I'd like to change things to avoid the twitch, but will leave this untouched now

**Comment by GazHank** [comment] 2021-04-06 00:25
A second Alpha build is now available, this should address the keyboard moving per the issue @davidm2m raised earlier.  It also allows for theme changes without a restart, among other changes.

@AlexDygma let me know if I can help at all getting the updated serialport & usb packages working on Mac.

I think I'll take another look at the preferences screen next to see what we can do to make it work nicely on large and small screens.  I also particularly like aspects of the screenshot from https://github.com/keyboardio/Chrysalis/issues/681 so might see if we can create something similar.

**Comment by davidm2m** [comment] 2021-04-06 09:46
I didn't see anything new broken.

Change between themes work nicely, and now the keyboard don't move.

**Comment by AlexDygma** [comment] 2021-04-06 10:32
Hey @GazHank !

Awesome! ill troubleshoot the usb changes, don't worry, i have a working version with electron 11 and serialport/USB libraries to the latest version, so it should be easy to fix for me.

regarding keyboardio#681, ofc that look and feel is better, but we will have to use @media tags to format the content and with material UI seems a bit troublesome. Still worth a try

**Comment by davidm2m** [comment] 2021-04-06 10:55
@GazHank , I was making some changes in my Raise layers configuration and I see that the colour of the key border when it is selected is very similar to the background, and I think that will be changed to a more bright colour.

**Comment by GazHank** [comment] 2021-04-06 12:59
@AlexDygma just shout if I can help at all with the debugging :-)

Regarding the sliders vs text boxes, I was trying to simplify things, but am not sure what would work best.  I was finding the textboxes seemed like Expert mode (as a novice user I'd like to know what is fast / slow / medium / default).  It also looks like we permit very wide ranges of values, far more than needed.  For example ranges from 1ms to 65000ms (65 seconds).  If we can shrink the range of permitted values to something more reasonable then we could get away with a slider to provide enough fine grained control?

I'll have another toy around with the layout and can always revert it to textboxes it would be pretty quick to pull the textbox code back in.

@davidm2m Thanks for the suggestion, I'll tweak the highlighting (I've made it #ff4081 and a little wider).  For now I've just hardcoded this as there isn't a quick way to add the theme info without risking breaking something else.  The other challenge with a long term fix for this, is the problem that the user can select absolutely any colour for the key themselves, so there is nothing stopping them using the highlight colour themselves (changing our highlighting to dynamically compensate for this would be a little harder).

**Comment by AlexDygma** [comment] 2021-04-08 12:31
Ok! let's go for it!

ill merge this on a different branch to add more tweaks like:

- As we discussed, further limit the maximum amount of milliseconds for the delay (maybe 2000 is enough)
- Add the functionality improvements to the macros that where merged on the las minute for 0.3.1
- Change the package versions for some of the libraries to make it mor compatible.

You did an outstanding job @GazHank !

**Comment by GazHank** [comment] 2021-04-10 20:07
@AlexDygma, that's great, thanks for merging these changes.  I'll certainly try to keep future suggested changes to much smaller more manageable pieces :-)

Speaking of which, I've some prototype screens for preferences I'd like to get some feedback on if you have time:

Wide screen:
![image](https://user-images.githubusercontent.com/64541249/114283159-3dc77b80-9a40-11eb-8020-469ef280419f.png)

Medium screen:
![image](https://user-images.githubusercontent.com/64541249/114283174-4fa91e80-9a40-11eb-8289-4b59f9aed238.png)

Narrow screen:
![image](https://user-images.githubusercontent.com/64541249/114283191-694a6600-9a40-11eb-9b3c-2458430e383f.png)

Of course it also works in white:
![image](https://user-images.githubusercontent.com/64541249/114283214-7ff0bd00-9a40-11eb-94a8-de42d13158bb.png)

Happy to raise this in a separate enhancement suggestion

Cheers

Gareth

**Comment by davidm2m** [comment] 2021-04-19 17:09
I was taking a look of 0.3.2 version and I think this issue is ready to be closed @AlexDygma and @GazHank .

Thanks for made available the dark theme. :)

**Closed** 2021-04-20 07:51 UTC
Labels: enhancement
