### ISSUE TITLE
Macro / Multiple Key-press bindings

### ISSUE THREAD

**Issue by jasonmelton** [Dygmalab/Bazecor#27] opened 2020-01-07 09:41 UTC
I would like to be able to use Bazecor to program macros.

I would prefer not to have to run a secondary program like Karabiner or Keyboard Maestro.

**Comment by algernon** [comment] 2020-01-22 10:20
This is on [on the roadmap](https://trello.com/c/1MRBdJlI/16-design-the-ui-ux-for-macros), FWIW. The firmware side of the feature is already implemented, and will be part of the next firmware update. The Bazecor side will be coming a bit later, because we need to come up with a decent way to present macro editing within the app.

**Comment by fklement** [comment] 2020-09-03 12:01
Is there already an update about the status of this?

**Comment by AlexDygma** [comment] 2020-10-14 11:01
Hello @fklement, we are just working on this feature right now 👍

**Comment by fklement** [comment] 2020-10-14 11:11
@AlexDygma Super cool! Thank's for the update. Really looking forward to this.

**Comment by oheydrew** [comment] 2020-10-15 06:23
That's great news :) 

> for now the macro key wont allow modifiers, but that will be a future feature to be added to the issue list

The use case I'm thinking of would be to have a key which both fires a basic key, AND moves to a layer. Is this likely to be possible?

**Comment by AlexDygma** [comment] 2020-10-15 08:26
> That's great news :)
> 
> > for now the macro key wont allow modifiers, but that will be a future feature to be added to the issue list
> 
> The use case I'm thinking of would be to have a key which both fires a basic key, AND moves to a layer. Is this likely to be possible?

If i understood that correctly, i think you are already capable of doing that with the option of layer shift when held, normal key otherwise.

Or maybe you want both effects at the same time? the macro system is flexible enough to reproduce any action that the keyboard is already capable of doing, it's a matter of supporting it in the UI. if you want to experiment with the focus library to test the functionality you are expecting, that will also be possible, even modding with specific actions not yet configurable through bazecor the macros you already made. I'll list this possibilities in the README.md file.

**Comment by oheydrew** [comment] 2020-10-15 08:55
Thanks @AlexDygma! That sounds positive. You're correct in that I'd like to see both trigger at once. I'm not yet familiar with the focus library- I'll take a look. Any info you can provide in the README will be super useful. Love a well-documented system! 👏

**Comment by AlexDygma** [comment] 2020-10-30 14:02
Hello Everyone! we are starting a Beta for the macro functionality, its ready to be tested and will be shared with more users in this [reddit](https://reddit.com/r/DygmaLab/comments/jkx1ln/macros_are_ready_for_testing/) post.

### take the following steps to test this version:
- Download from reddit or locally compile the current Bazecor branch #105 
- Flash the Firmware provided in that Bazecor version to enable Macro functionality
- Configure a key as Macro and create a macro / test it
- Post any issues found here in git or in the reddit post.

Happy MacroING 😎

**Closed** 2020-11-09 13:48 UTC
Labels: enhancement
