### ISSUE TITLE
Could not build in Windows; Bazecor\node_modules\nan\nan_converters_43_inl.h(22,1): error C2664

### ISSUE THREAD

**Issue by usagi** [Dygmalab/Bazecor#24] opened 2020-01-01 11:58 UTC
**Describe the bug**
Could not build using `yarn` in Windows.

**To Reproduce**
1. Install VS2019 Community -> VS2019-16.4.29613.14
2. Install chocolately -> chocolately-0.10.15
3. `choco install python` -> ptyhon-3.8.1
4. `choco install nodejs` -> nodejs-13.5.0
5. `choco install yarn` -> yarn-1.21.1
6. `git clone git@github.com:Dygmalab/Bazecor.git`
7. `cd Bazecor`
8. `yarn` <-- Error!

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/115972/71641050-b5a0e500-2cd8-11ea-80ae-da4aca654661.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit 10.0.18362.535
 - Bazecor Version: latest master 868c3e6b9578b0765f090a618c65275875eee1be

**Additional context**

Full log is here: <https://gist.github.com/usagi/551385f199370199c1bc4a139e4c06b1>

**Comment by stemsmit** [comment] 2020-01-01 19:29
This is caused by the dependency serialport in v6 I think the issue has been fixed in v8.

Upgrading these would get that error to go away:

- [@bazecore/focus](https://www.npmjs.com/package/@bazecor-api/focus)'s dependency 
	- [serialport](https://www.npmjs.com/package/serialport)@^6.2.2 -> serialport@^8.0.6
- [avrgirl-arduino](https://github.com/noopkat/avrgirl-arduino)@^3.0.0 -> avrgirl-arduino@^4.0.0

**Comment by usagi** [comment] 2020-01-02 13:26
Thanks @stemsmit for your hints. I'm trying solve the issue now continuously. But it's complicated because I occured https://github.com/tessel/node-usb/issues/347 after the first fixing of serialport dependency. 😭

I'll PR if I solve all problems. But, it may need more times. Maybe, I know I can build more easily if use mingw or WSL2( /dev supported ) or raw GNU/Lnux or OSX. However I desire build it with methods in common Windows users include Japanese environments.

**Comment by algernon** [comment] 2020-01-22 10:15
From my quick experiments, simply upgrading serialport will not be enough. It did make the compile step succeed, but the resulting application was not able to connect to the Raise. We'll have to dive a bit deeper to figure out what's going on, and how to upgrade to a newer version of the serialport package :/

For the time being, using Node earlier than 12 is a possible workaround.

**Comment by Mywk** [comment] 2020-02-15 01:03
Compiling fine for me with the following versions:
VS2019-16.4.29613.14
Python 3.7.4
Yarn 1.22.0
Node.js v12.16.0

**Comment by elfmimi** [comment] 2020-04-16 15:43
node-usb upstream has released new version 1.6.3 few days ago.
Please update package.json accordingly.

**Comment by usagi** [comment] 2020-04-17 16:00
@elfmimi Thanks for the notifing. I'll try to update the usb package and I'll PR if it is well.

**Comment by usagi** [comment] 2020-04-17 16:06
`yarn` works fine **with update the usb package to 1.6.3** . I'll PR soon, and then the issue be solved maybe. 🎉

**Closed** 2020-11-09 14:32 UTC
Labels: bug, help wanted
